name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh root@"${{ secrets.SERVER_HOST }} << 'EOF'
          set -e
          cd /root/learnit
          git fetch origin main
          git reset --hard origin/main
          docker compose up -d --build
          EOF
